batch_size: 32
prompt_len: 4096

tensor_parallel_size: 1
data_parallel_size: 8
enable_expert_parallel: true
all2all_backend: allgather_reducescatter
kv_cache_memory_bytes: 4294967296
warmup_iters: 3
profile_iters: 1
profile: none
profiler_with_stack: true
gpu_count: 8
random_seed: 0
